scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: range1
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.52
        upper_angle: 1.52
        